config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'forums#index'
  resources :forums do
    resources :comments
  end
  resources :tags, only: [:index, :show]
  get '/tagged', to: "forums#tagged", as: :tagged

  resources :comments do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

app/models/forum.rb
class Forum < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, as: :commentable
  acts_as_taggable_on :tags
end

app/models/user.rb
class User < ApplicationRecord
 has_many :forums, dependent: :nullify
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  skip_before_action :verify_authenticity_token, if: :json_request?
  
  before_action :find_current_user
  
  private

  def find_current_user
     @user = User.find_by_session_id(session&.id)
  end

  def json_request?
    request.format.json?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_commentable

  def new
    @forum = Forum.find(params[:id])
    @comment = Comment.new
  end

  def create
    @commentable.comments.build(comment_params)
    if @commentable.save
      redirect_back(fallback_location: root_path)
    else
      flash[:notice] = 'sorry could not '
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_commentable
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable = Forum.find_by_id(params[:forum_id]) if params[:forum_id]
  end

  
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]
  # before_action :find_user, only: [:create]


  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
  end

  # GET /forums/new
  def new
    @forum = Forum.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = @user.forums.new(forum_params)

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render :show, status: :created, location: @forum }
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  def tagged
    if params[:tag].present?
      @forums = Forum.tagged_with(params[:tag])
    else
      @forums = Forum.all
    end
  end
  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find_by_id(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def forum_params
      params.require(:forum).permit(:user_id, :title, :body, :tag_list)
    end  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
        @tags = ActsAsTaggableOn::Tag.all
    end

    def show
        @tag =  ActsAsTaggableOn::Tag.find_by_id(params[:id])
        @forums = Forum.tagged_with(@tag.name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/acts_as_taggable_on/tags/_tag.html.erb
<%= link_to tag.name, tag_path(tag) %>

app/views/comments/_comment.html.erb
<li>
  <%= comment.body %>

  <%= form_for [comment, Comment.new] do |f| %>
  <div class="form-group">
      <%= f.text_area :body, placeholder: "Add a Reply", class: "form-control" %><br/>
      <%= f.submit 'Submit', class: "btn btn-primary sm" %>
      <% end %>
  </div>

  <ul>
      <%= render partial: 'comments/comment', collection: comment.comments %>
  </ul>

</li>

app/views/forums/_form.html.erb
  <div class='container-fluid'>
    <div class="col-md-8">
    <%= form_with(model: forum, local: true) do |form| %>
      <% if forum.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

          <ul>
            <% forum.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= form.label :title, class: "col-sm-2 col-form-label col-form-label-lg" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :body, class: "col-sm-2 col-form-label col-form-label-lg" %>
        <%= form.text_area :body, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :tags, class: "col-sm-2 col-form-label col-form-label-lg" %>
        <%= form.text_field :tag_list, value: @forum.send(:tag_list).to_s, class: "form-control" %>
        <small id="emailHelp" class="form-text text-muted">user comma separated values to indicate the category your post is about e.g candida.</small>
      </div>

      <div class="actions">
        <%= form.submit 'submit', class: "btn btn-primary"%>
      </div>
    <% end %>
  </div>
  </div>

app/views/forums/_forum.html.erb
<h2><%= link_to forum.title, forum_path(forum) %></h2>

app/views/forums/edit.html.erb
<h1>Editing Forum</h1>

<%= render 'form', forum: @forum %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<p id="notice"><%= notice %></p>
<div class="list-group">
<div class="overflow-auto">
  
  <% @forums&.each do |forum| %>
   <div class="forum-item">
      <%= link_to forum, class: "list-group-item list-group-item-action" do %>
        <div class="d-flex w-100 justify-content-between ">
          <h5 class="mb-1"><b><%= forum&.title %></b></h5>
          <small><b></b>posted by: <%= forum&.user&.nick_name %></small>
        </div>
        <p class="mb-1"><%= forum&.body %></p>
        <small><b>Tags: </b><%= forum&.tag_list %></small>            
      <% end %>
    </div>
    <% end %>

  </div>
</div>
<%= link_to "New Forum", new_forum_path %>

app/views/forums/new.html.erb
<h1 class="text-monospace ">What is on your mind?<span class="far fa-smile"><span></h1>
<h5 class="text-monospace">Feel free to post anything or even ask a question. Your identity is concealed</h5>

<%= render 'form', forum: @forum %>

<%= link_to 'Back', forums_path %>

app/views/forums/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-3">
    <p>
      <strong>User:</strong>
      <%= @forum&.user&.nick_name %>
    </p>

    <p>
      <strong>Title:</strong>
      <%= @forum&.title %>
    </p>

    <p>
      <strong>Body:</strong>
      <%= @forum&.body %>
    </p>

    <p>
      <strong>Tags:</strong>
      <%= @forum&.tag_list %>
    </p>

    <div><%= @forum&.tag_list %></div>
    <%= form_for [ @forum, Comment.new] do |f| %>
          <%= f.text_area :body, placeholder: "Add a comment" , class: 'form-control'%>
          <%= f.submit "Add Comment", class: "btn btn-primary" %>
        <% end %>
    <ul>
    <%= render partial: 'comments/comment', collection: @forum.comments %>
    </ul>


    <%= link_to 'Edit', edit_forum_path(@forum) %> |
    <%= link_to 'Back', forums_path %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeFree</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header'%>
    <div class="container">
      <% if notice %>
       <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
          <% end %>
      <%= yield %>
    </div>
    <%= render 'shared/footer'%>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="navbar fixed-bottom">
  <div class="container">
    Be Free <%= Time.now.year %>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="https://still-mountain-95524.herokuapp.com/">Be Free App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
         
        <li class="nav-item">
           <%= link_to "Discussions", '/', :class => 'nav-link'  %> 
        </li>
        <li class="nav-item">
           <%= link_to "New Discussion", new_forum_path, :class => 'nav-link'  %> 
        </li>
    </ul>
         <span class="navbar-text">
        <ul class="navbar-nav mr-auto">
           <li class="nav-item">
         <%= link_to "Appointments", 'https://dry-fortress-76246.herokuapp.com/', :class => 'navbar-link', :class => 'nav-link' %>
        </li>
         <li class="nav-item">
          <%= link_to "Payments", 'https://secure-cliffs-28598.herokuapp.com/', :class => 'navbar-link', :class => 'nav-link'%>
        </li> 
        </ul>
        </span>     
  </div>
</nav>

app/views/tags/index.html.erb
<h1>Tags</h1>
<%= render @tags %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>
<div><%= render @forums %></div>